# Default values for glasskube-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

glasskubeOperator:
  image:
    repository: glasskube/operator
    tag: "" # defaults to Chart.appVersion if unspecified
  replicaCount: 1
  resources:
    limits:
      cpu: 1000m
      memory: 640Mi
    requests:
      cpu: 100m
      memory: 64Mi

cert-manager:
  enabled: false
  installCRDs: true

cloudnative-pg:
  enabled: false

kube-prometheus-stack:
  enabled: false
  prometheus:
    prometheusSpec:
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            resources:
              requests:
                storage: 10Gi
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false
  grafana:
    ingress:
      enabled: true
      # annotations:
      #   cert-manager.io/cluster-issuer: issuer-name
      # ingressClassName: nginx
      # hosts:
      #   - grafana.example.com
      # tls:
      #   - hosts:
      #       - grafana.example.com
      #     secretName: grafana-tls
    persistence:
      enabled: true
      size: 10Gi

mariadb-operator:
  enabled: false
  # clusterName: cluster.local
  ha:
    enabled: false
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false
  webhook:
    serviceMonitor:
      enabled: false

minio:
  enabled: true
  # clusterDomain: cluster.local
  replicas: 1
  mode: standalone
  persistence:
    size: 20Gi
  DeploymentUpdate:
    type: Recreate
  resources:
    requests:
      memory: 256Mi
